Repository crossoverJie/cim, pull requests merged in 2019-01, with the labels that each got.

#16 cim 1.0.1
  cim-client/pom.xml
  cim-client/src/main/java/com/crossoverjie/cim/client/config/AppConfiguration.java
  cim-client/src/main/java/com/crossoverjie/cim/client/config/BeanConfig.java
  cim-client/src/main/java/com/crossoverjie/cim/client/handle/CIMClientHandle.java
  cim-client/src/main/java/com/crossoverjie/cim/client/init/CIMClientHandleInitializer.java
  cim-client/src/main/java/com/crossoverjie/cim/client/scanner/Scan.java
  cim-client/src/main/java/com/crossoverjie/cim/client/service/MsgLogger.java
  cim-client/src/main/java/com/crossoverjie/cim/client/service/impl/AsyncMsgLogger.java
  cim-client/src/main/java/com/crossoverjie/cim/client/service/impl/MsgCallBackListener.java
  cim-client/src/main/java/com/crossoverjie/cim/client/service/impl/MsgHandler.java
  cim-client/src/main/java/com/crossoverjie/cim/client/service/impl/RouteRequestImpl.java
  cim-client/src/main/resources/application.properties
  cim-client/src/test/com/crossoverjie/cim/client/service/impl/AsyncMsgLoggerTest.java
  cim-client/src/test/com/crossoverjie/cim/server/test/CommonTest.java
  cim-common/src/main/java/com/crossoverjie/cim/common/data/construct/TrieTree.java
  cim-common/src/main/java/com/crossoverjie/cim/common/enums/StatusEnum.java
  cim-common/src/main/java/com/crossoverjie/cim/common/enums/SystemCommandEnumType.java
  cim-common/src/main/java/com/crossoverjie/cim/common/protocol/CIMResponseProto.java
  cim-common/src/test/java/com/crossoverjie/cim/common/data/construct/TrieTreeTest.java
  cim-forward-route/pom.xml
  cim-forward-route/src/main/java/com/crossoverjie/cim/route/controller/RouteController.java
  cim-forward-route/src/main/java/com/crossoverjie/cim/route/service/AccountService.java
  cim-forward-route/src/main/java/com/crossoverjie/cim/route/service/impl/AccountServiceRedisImpl.java
  cim-forward-route/src/test/java/com/crossoverjie/cim/route/service/impl/AccountServiceRedisImplTest.java
  cim-server/pom.xml
  cim-server/src/main/java/com/crossoverjie/cim/server/config/AppConfiguration.java
  cim-server/src/main/java/com/crossoverjie/cim/server/config/BeanConfig.java
  cim-server/src/main/java/com/crossoverjie/cim/server/handle/CIMServerHandle.java
  cim-server/src/main/java/com/crossoverjie/cim/server/init/CIMServerInitializer.java
  cim-server/src/main/java/com/crossoverjie/cim/server/util/NettyAttrUtil.java
  cim-server/src/main/resources/application.properties
  cim-server/src/test/com/crossoverjie/cim/server/util/NettyAttrUtilTest.java
  protocol/BaseResponseProto.proto
Labels: enhancement, new features

#15 Added a visualisation of code evolution
  README.md
Labels: enhancement

#26 Cim 1.0.2
  cim-client/pom.xml
  cim-client/src/main/java/com/crossoverjie/cim/client/CIMClientApplication.java
  cim-client/src/main/java/com/crossoverjie/cim/client/client/CIMClient.java
  cim-client/src/main/java/com/crossoverjie/cim/client/config/AppConfiguration.java
  cim-client/src/main/java/com/crossoverjie/cim/client/config/BeanConfig.java
  cim-client/src/main/java/com/crossoverjie/cim/client/handle/CIMClientHandle.java
  cim-client/src/main/java/com/crossoverjie/cim/client/init/CIMClientHandleInitializer.java
  cim-client/src/main/java/com/crossoverjie/cim/client/service/MsgHandle.java
  cim-client/src/main/java/com/crossoverjie/cim/client/service/RouteRequest.java
  cim-client/src/main/java/com/crossoverjie/cim/client/service/impl/ClientHeartBeatHandlerImpl.java
  cim-client/src/main/java/com/crossoverjie/cim/client/service/impl/ClientInfo.java
  cim-client/src/main/java/com/crossoverjie/cim/client/service/impl/MsgHandler.java
  cim-client/src/main/java/com/crossoverjie/cim/client/service/impl/RouteRequestImpl.java
  cim-client/src/main/java/com/crossoverjie/cim/client/thread/ReConnectJob.java
  cim-client/src/main/resources/application.properties
  cim-common/pom.xml
  cim-common/src/main/java/com/crossoverjie/cim/common/enums/SystemCommandEnumType.java
  cim-common/src/main/java/com/crossoverjie/cim/common/kit/HeartBeatHandler.java
  cim-common/src/main/java/com/crossoverjie/cim/common/util/NettyAttrUtil.java
  cim-forward-route/src/main/java/com/crossoverjie/cim/route/service/impl/AccountServiceRedisImpl.java
  cim-server/pom.xml
  cim-server/src/main/java/com/crossoverjie/cim/server/config/BeanConfig.java
  cim-server/src/main/java/com/crossoverjie/cim/server/handle/CIMServerHandle.java
  cim-server/src/main/java/com/crossoverjie/cim/server/init/CIMServerInitializer.java
  cim-server/src/main/java/com/crossoverjie/cim/server/kit/RouteHandler.java
  cim-server/src/main/java/com/crossoverjie/cim/server/kit/ServerHeartBeatHandlerImpl.java
  cim-server/src/main/resources/application.properties
  pom.xml
  springboot-admin/README.md
  springboot-admin/pom.xml
  springboot-admin/src/main/java/com/ai/obc/springboot/admin/AdminApplication.java
  springboot-admin/src/main/resources/application.properties
  springboot-admin/src/test/java/com/ai/obc/springboot/admin/AdminApplicationTests.java
Labels: new features

#27 cim 1.0.3
  cim-client/src/main/java/com/crossoverjie/cim/client/client/CIMClient.java
  cim-client/src/main/java/com/crossoverjie/cim/client/service/InnerCommand.java
  cim-client/src/main/java/com/crossoverjie/cim/client/service/InnerCommandContext.java
  cim-client/src/main/java/com/crossoverjie/cim/client/service/MsgHandle.java
  cim-client/src/main/java/com/crossoverjie/cim/client/service/impl/MsgHandler.java
  cim-client/src/main/java/com/crossoverjie/cim/client/service/impl/command/CloseAIModelCommand.java
  cim-client/src/main/java/com/crossoverjie/cim/client/service/impl/command/EchoInfoCommand.java
  cim-client/src/main/java/com/crossoverjie/cim/client/service/impl/command/OpenAIModelCommand.java
  cim-client/src/main/java/com/crossoverjie/cim/client/service/impl/command/PrefixSearchCommand.java
  cim-client/src/main/java/com/crossoverjie/cim/client/service/impl/command/PrintAllCommand.java
  cim-client/src/main/java/com/crossoverjie/cim/client/service/impl/command/PrintOnlineUsersCommand.java
  cim-client/src/main/java/com/crossoverjie/cim/client/service/impl/command/QueryHistoryCommand.java
  cim-client/src/main/java/com/crossoverjie/cim/client/service/impl/command/ShutDownCommand.java
  cim-client/src/test/com/crossoverjie/cim/client/service/InnerCommandContextTest.java
  cim-common/src/main/java/com/crossoverjie/cim/common/enums/SystemCommandEnum.java
  cim-common/src/test/java/com/crossoverjie/cim/common/enums/SystemCommandEnumTypeTest.java
  cim-forward-route/src/main/java/com/crossoverjie/cim/route/controller/RouteController.java
Labels: new features
