Repository crossoverJie/cim, pull requests merged in 2024-09, with the labels that each got.

#146 Refactor proxy manager
  README.md
  cim-client/src/main/java/com/crossoverjie/cim/client/client/CIMClient.java
  cim-client/src/main/java/com/crossoverjie/cim/client/config/BeanConfig.java
  cim-client/src/main/java/com/crossoverjie/cim/client/controller/IndexController.java
  cim-client/src/main/java/com/crossoverjie/cim/client/scanner/Scan.java
  cim-client/src/main/java/com/crossoverjie/cim/client/service/InnerCommand.java
  cim-client/src/main/java/com/crossoverjie/cim/client/service/MsgHandle.java
  cim-client/src/main/java/com/crossoverjie/cim/client/service/RouteRequest.java
  cim-client/src/main/java/com/crossoverjie/cim/client/service/impl/MsgHandler.java
  cim-client/src/main/java/com/crossoverjie/cim/client/service/impl/RouteRequestImpl.java
  cim-client/src/main/java/com/crossoverjie/cim/client/service/impl/command/PrefixSearchCommand.java
  cim-client/src/main/java/com/crossoverjie/cim/client/service/impl/command/PrintOnlineUsersCommand.java
  cim-client/src/main/java/com/crossoverjie/cim/client/service/impl/command/ShutDownCommand.java
  cim-client/src/main/java/com/crossoverjie/cim/client/vo/req/GroupReqVO.java
  cim-client/src/main/java/com/crossoverjie/cim/client/vo/req/LoginReqVO.java
  cim-client/src/main/java/com/crossoverjie/cim/client/vo/req/P2PReqVO.java
  cim-client/src/main/java/com/crossoverjie/cim/client/vo/req/SendMsgReqVO.java
  cim-client/src/main/java/com/crossoverjie/cim/client/vo/res/CIMServerResVO.java
  cim-client/src/main/java/com/crossoverjie/cim/client/vo/res/OnlineUsersResVO.java
  cim-client/src/main/resources/application.yaml
  cim-client/src/test/java/com/crossoverjie/cim/client/service/InnerCommandContextTest.java
  cim-client/src/test/java/com/crossoverjie/cim/server/test/CommonTest.java
  cim-client/src/test/java/com/crossoverjie/cim/server/test/RouteTest.java
  cim-common/pom.xml
  cim-common/src/main/java/com/crossoverjie/cim/common/core/proxy/ProxyManager.java
  cim-common/src/main/java/com/crossoverjie/cim/common/core/proxy/Request.java
  cim-common/src/main/java/com/crossoverjie/cim/common/core/proxy/RpcProxyManager.java
  cim-common/src/main/java/com/crossoverjie/cim/common/enums/StatusEnum.java
  cim-common/src/main/java/com/crossoverjie/cim/common/pojo/CIMUserInfo.java
  cim-common/src/main/java/com/crossoverjie/cim/common/util/HttpClient.java
  cim-common/src/test/java/com/crossoverjie/cim/common/core/proxy/RpcProxyManagerTest.java
  cim-forward-route/src/main/java/com/crossoverjie/cim/route/controller/RouteController.java
  cim-forward-route/src/main/java/com/crossoverjie/cim/route/service/impl/AccountServiceRedisImpl.java
  cim-integration-test/src/test/java/com/crossoverjie/cim/client/ClientTest.java
  cim-rout-api/src/main/java/com/crossoverjie/cim/route/api/RouteApi.java
  cim-rout-api/src/main/java/com/crossoverjie/cim/route/api/vo/req/ChatReqVO.java
  cim-rout-api/src/main/java/com/crossoverjie/cim/route/api/vo/req/LoginReqVO.java
  cim-rout-api/src/main/java/com/crossoverjie/cim/route/api/vo/res/CIMServerResVO.java
  cim-server-api/src/main/java/com/crossoverjie/cim/server/api/ServerApi.java
  cim-server/src/main/java/com/crossoverjie/cim/server/kit/RouteHandler.java
Labels: enhancement

#147 Modify the consistent hash
  cim-common/src/main/java/com/crossoverjie/cim/common/route/algorithm/consistenthash/AbstractConsistentHash.java
  cim-common/src/main/java/com/crossoverjie/cim/common/route/algorithm/consistenthash/SortArrayMapConsistentHash.java
  cim-common/src/main/java/com/crossoverjie/cim/common/route/algorithm/consistenthash/TreeMapConsistentHash.java
  cim-common/src/test/java/com/crossoverjie/cim/common/route/algorithm/consistenthash/RangeCheckTestUtil.java
  cim-common/src/test/java/com/crossoverjie/cim/common/route/algorithm/consistenthash/SortArrayMapConsistentHashTest.java
  cim-common/src/test/java/com/crossoverjie/cim/common/route/algorithm/consistenthash/TreeMapConsistentHashTest.java
Labels: bug

#151 Support dynamic url
  cim-common/src/main/java/com/crossoverjie/cim/common/core/proxy/DynamicUrl.java
  cim-common/src/main/java/com/crossoverjie/cim/common/core/proxy/RpcProxyManager.java
  cim-common/src/test/java/com/crossoverjie/cim/common/core/proxy/RpcProxyManagerTest.java
  cim-forward-route/src/main/java/com/crossoverjie/cim/route/service/impl/AccountServiceRedisImpl.java
  cim-server-api/src/main/java/com/crossoverjie/cim/server/api/ServerApi.java
  cim-server/src/main/java/com/crossoverjie/cim/server/controller/IndexController.java
Labels: enhancement

#149 feature:support offline atomic command by lua
  cim-forward-route/src/main/java/com/crossoverjie/cim/route/service/UserInfoCacheService.java
  cim-forward-route/src/main/java/com/crossoverjie/cim/route/service/impl/AccountServiceRedisImpl.java
  cim-forward-route/src/main/java/com/crossoverjie/cim/route/service/impl/UserInfoCacheServiceImpl.java
  cim-forward-route/src/main/resources/lua/offLine.lua
  cim-forward-route/src/test/java/com/crossoverjie/cim/route/service/impl/UserInfoCacheServiceImplTest.java
Labels: enhancement

#154 feature:Use_Spring_IOC_to_refactor_RpcProxyManager
  cim-forward-route/src/main/java/com/crossoverjie/cim/route/config/BeanConfig.java
  cim-forward-route/src/main/java/com/crossoverjie/cim/route/service/impl/AccountServiceRedisImpl.java
  cim-server/src/main/java/com/crossoverjie/cim/server/config/BeanConfig.java
  cim-server/src/main/java/com/crossoverjie/cim/server/kit/RouteHandler.java
Labels: enhancement

#153 fix:User_Logout_NPE
  cim-client-sdk/src/test/java/com/crossoverjie/cim/client/sdk/ClientTest.java
  cim-forward-route/src/main/java/com/crossoverjie/cim/route/controller/RouteController.java
  cim-forward-route/src/main/java/com/crossoverjie/cim/route/service/UserInfoCacheService.java
  cim-forward-route/src/main/java/com/crossoverjie/cim/route/service/impl/AccountServiceRedisImpl.java
  cim-forward-route/src/main/java/com/crossoverjie/cim/route/service/impl/UserInfoCacheServiceImpl.java
Labels: bug, enhancement

#156 feature:Support_LRU_User_Info_Cache
  cim-forward-route/src/main/java/com/crossoverjie/cim/route/config/BeanConfig.java
  cim-forward-route/src/main/java/com/crossoverjie/cim/route/service/impl/UserInfoCacheServiceImpl.java
Labels: enhancement

#155 feature:Support_reconnect_backoff_interface
  cim-client-sdk/src/main/java/com/crossoverjie/cim/client/sdk/ClientBuilder.java
  cim-client-sdk/src/main/java/com/crossoverjie/cim/client/sdk/impl/ClientBuilderImpl.java
  cim-client-sdk/src/main/java/com/crossoverjie/cim/client/sdk/impl/ClientConfigurationData.java
  cim-client-sdk/src/main/java/com/crossoverjie/cim/client/sdk/impl/ClientImpl.java
  cim-client-sdk/src/main/java/com/crossoverjie/cim/client/sdk/io/backoff/BackoffStrategy.java
  cim-client-sdk/src/main/java/com/crossoverjie/cim/client/sdk/io/backoff/RandomBackoff.java
  cim-client-sdk/src/test/java/com/crossoverjie/cim/client/sdk/ClientTest.java
  cim-client/src/main/java/com/crossoverjie/cim/client/config/BeanConfig.java
  cim-client/src/main/resources/application.yaml
Labels: enhancement

#161 Optimize client message
  cim-client-sdk/src/main/java/com/crossoverjie/cim/client/sdk/io/CIMClientHandle.java
  cim-client-sdk/src/main/java/com/crossoverjie/cim/client/sdk/io/backoff/RandomBackoff.java
  cim-client/src/main/java/com/crossoverjie/cim/client/config/BeanConfig.java
  cim-client/src/main/java/com/crossoverjie/cim/client/service/impl/EchoServiceImpl.java
  cim-client/src/main/java/com/crossoverjie/cim/client/service/impl/MsgCallBackListener.java
  cim-forward-route/src/main/java/com/crossoverjie/cim/route/controller/RouteController.java
Labels: enhancement
